# Generated by Django 4.1 on 2022-08-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
            ],
        ),
    ]
